### ISSUE TITLE
Frequent "offline" status causing subnet router re-election and connection disruptions

### ISSUE THREAD

**Issue by vsychov** [juanfont/headscale#1501] opened 2023-06-30 21:15 UTC
Hello,

I have noticed a recurring issue where I often see console messages from headscale indicating that a machine has gone "offline", even though the machine is actually online and has no issues with its internet connection. As I am using tailscale as a subnet router, this results in re-election of the "primary route" if such a machine was being used as the "primary route", leading to connection disruptions.

It appears that the problem lies in how a machine is set to "offline" mode, using the `last_seen` field in the database. A machine goes offline when the `last_seen` field reaches a value of 60 seconds (`keepAliveInterval`). Therefore, even a slight delay of just an extra second can make the machine go offline, leading to a new subnet router being elected.

It looks like field `last_seen` updated in `keepAliveTicker` and few other places, and it's happens each 40-60 seconds in my setup, that's not enough.

From what I can see, this problem could be solved by updating the `last_seen` field in the `updateCheckerTicker` (which by default occurs every 10 seconds - `NodeUpdateCheckInterval`), simply by adding:
```go
machine.LastSeen = &now
```
right after:
https://github.com/juanfont/headscale/blob/fe75b716201a2d31bd8fe2531100e93ff7bfb4f1/hscontrol/poll.go#L561

I hope this suggestion is helpful and look forward to any feedback.

Thank you

**Comment by kradalby** [comment] 2023-07-07 14:18
This might be fixed, or we might have the base to fix this when #1492 land, it starts looking at the Online field, and sends update in a different way. It might not have been directly addressed, but should be easier to fix.

**Comment by kradalby** [comment] 2024-01-19 08:35
@andreyrd we follow common software release practices and alpha software is not recommended to use in production, we need help testing it so we release it under a alpha/beta label to imply that you need to be cautious using this.

I believe the issue has been solved, but we need people who encounter the problem to test it, if you have the opportunity, that would be great.

**Comment by kradalby** [comment] 2024-02-19 14:06
Could you please test if this is still the case with https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5 ?

**Comment by eNdiD** [comment] 2024-02-27 08:49
@kradalby with the latest 0.23.5-alpha5 there is an odd behavior. I constantly see my android clients go offline while they continue to work fine with the tailnet. But Headscale seems to stop sending updates to them. To make them become online again they need to send some updates by themselves, like moving to a different network, or if I manually restart Tailscale connection on them.

Once I've seen the very same on my Raspberry Pi, but only once, and I'm not sure what the cause was. Other linux clients stay online without an issue.

**Comment by fortitudepub** [comment] 2024-03-19 02:26
I also found this issue with the 0.23.5+ version, by some investigation, I think it may be caused by existing connection to controller have been reset (by switching the router /wifi because it may switch the NAT outside address or other reasons) and meanwhile the new connection established quickly, in that case, in poll.go the old connection's defer action may be executed after e the new conection being added because the online status is now a map index by node key.www

**Comment by kradalby** [comment] 2024-04-17 06:25
Could you please try the newest alpha (https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha6) and report back?

**Comment by vsychov** [comment] 2024-04-18 07:54
Thanks @kradalby , I'll make tests today or tomorrow

**Comment by kradalby** [comment] 2024-05-24 09:10
I believe fixes in https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha12 should resolve this issue, let me now if not and we will reopen it.

**Closed by kradalby** 2024-05-24 09:10 UTC
Labels: bug, well described ❤️
