### ISSUE TITLE
Advertising and existing pre-authorised route does not enable it

### ISSUE THREAD

**Issue by tomtom5152** [juanfont/headscale#1655] opened 2023-12-15 17:28 UTC
## Context

This was discovered using the `k3s` tailscale integration, however I have manually replicated it using native tailscale commands.

## Bug description

When a route that is preauthorised by ACL `autoApprovers` it automatically get enabled as would be expected.

If the node then stops advertising it, the appropriate flags in the DB get set to `false`.

If the node starts advertising again, `Route.Advertised` correctly get set to true, however `Route.Enabled` remains false unless tailscale itself is restarted.

### Sample routes table entries

These are abbreviated database entries for what I am witnessing. I have omitted irrelevant information as it either does not change, or is of minimal significance (timestamps etc). All IP ranges fall within the ranges for `autoApprovers` on the node.

Event  | ID | prefix |  advertised | enabled | is_primary
---|---|---|---|---|---
Node first advertises | 1 | 198.51.100.0/24 | true | true | true
Node stops advertising | 1 | 198.51.100.0/24 | false | false | true
Node resumes advertising | 1 | 198.51.100.0/24 | true | false | true
Tailscaled is restart | 1 | 198.51.100.0/24 | true | true | true 

### Headscale host

- OS: Ubuntu 23.04 LTS arm64
- Headscale version: v0.23.0-alpha2
- Database: CockroachDB (also confirmed on Postgres and SQLite, just happen to be using CRDB)
- Confirmed with and without docker
- Confirmed with and without reverse proxy

### Tailscale hosts

OS | Tailscale version
----|----
Ubuntu 23.04 LTS arm64 | 1.56.0
OPNsense 23.7.8_1-amd64 | 1.54.0
Unraid 6.12.6 | 1.54.0

## To Reproduce

On a node appropriately labelled and in `autoApprovers`

`tailscale set --advertise-routes=198.51.100.0/24`
`tailscale set --advertise-routes=`
`tailscale set --advertise-routes=198.51.100.0/24`

To reenable the route (systemd)

`systemctl restart tailscaled`

**Comment by Apoorva64** [comment] 2023-12-18 17:17
+1, I've got the same issue

**Comment by kradalby** [comment] 2024-01-02 13:49
I think this should be fixed in https://github.com/juanfont/headscale/pull/1670, would be great if you give it a try.

**Comment by tomtom5152** [comment] 2024-01-14 01:13
Tested as it currently is in #1670 with k3s, appears to work perfectly but have only had limited testing.

**Comment by kradalby** [comment] 2024-01-18 16:33
Could you give 0.23.0-alpha3 a go and report back?

**Comment by kradalby** [comment] 2024-02-15 10:04
https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha4

**Comment by kradalby** [comment] 2024-02-19 14:05
Could you please test if this is still the case with https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5 ?

**Comment by ozeliurs** [comment] 2024-03-13 13:12
> Could you please test if this is still the case with https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5 ?

I cannot reproduce the problem on headscale v0.23.0-alpha5 and k3s v1.28.3+k3s2 thus I conclude this issue has been fixed.

If you need me to test a specific scenario concerning headscale and k3s do not hesitate to reach out to me.

Thanks a lot.

@Apoorva64

**Comment by linjanin** [comment] 2024-03-29 10:18
#1670 After routes changed, the instance of node doesn't set Routes field with the new routes value. Later, StatePeerChanged event emitted, mapper.tailNode function will retrieve routes from it to determining allowedIPs. It always leads the clients to receive previous advertised routes.

**Comment by kradalby** [comment] 2024-04-17 06:24
Could you please try the newest alpha (https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha6) and report back?

**Comment by kradalby** [comment] 2024-04-30 07:38
Could you try the newest alpha (https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha10) and report back? If we do not hear back I will assume it has been resolved.

**Comment by kradalby** [comment] 2024-05-24 09:10
I believe fixes in https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha12 should resolve this issue, let me now if not and we will reopen it.

**Closed by kradalby** 2024-05-24 09:10 UTC
Labels: bug

**Comment by Apoorva64** [comment] 2024-06-01 09:56
@kradalby Works for us on alpha12
