### ISSUE TITLE
Detailed logs

### ISSUE THREAD

**Issue by bharathmsd7** [juanfont/headscale#73] opened 2021-08-03 08:21 UTC
Is there is any way to find more detailed logs, 
becoz in **`headscale serve`** it shows just like **Successfully authenticated via AuthKey**
But in peer `tailscale up -login-server HEADSCALE_URL --authkey AUTHKEY` got hanged.

_Originally posted by @bharathmsd7 in https://github.com/juanfont/headscale/issues/70#issuecomment-891172764_

**Comment by kradalby** [comment] 2021-08-03 16:22
I suspect this is a duplicate of #50

**Comment by juanfont** [comment] 2021-08-05 22:28
@bharathmsd7 Can you please try with v0.5.0? https://github.com/juanfont/headscale/releases/tag/v0.5.0

**Comment by qbit** [comment] 2021-08-05 22:43
new log stuff looks terribad if your system doesn't show colors:
```
Aug  5 16:42:22 foof headscale[88728]: \^[[90m2021-08-05T22:42:22Z\^[[0m \^[[33mDBG\^[[0m Sending keepalive \^[[36mfunc=\^[[0mkeepAlive \^[[36mmachine=\^[[0mtal
```

**Comment by kradalby** [comment] 2021-08-06 06:01
@qbit ah sorry, ill make it configurable

**Comment by kradalby** [comment] 2021-08-06 06:31
@qbit Could you give #76 a whirl?

**Comment by qbit** [comment] 2021-08-06 11:24
@kradalby that did it! ty!

**Comment by bharathmsd7** [comment] 2021-08-06 11:29
> @bharathmsd7 Can you please try with v0.5.0? https://github.com/juanfont/headscale/releases/tag/v0.5.0

Now its better man
Thanks !

**Closed** 2021-08-07 22:14 UTC
