### ISSUE TITLE
Can not get the lets encrypt part to work.

### ISSUE THREAD

**Issue by urskog84** [juanfont/headscale#138] opened 2021-10-03 17:08 UTC
Hi!

Any one more then me having problem setup ssl?

I get the folowing hint in the log?
```
headscale    | 2021/10/03 17:05:22 http: TLS handshake error from 192.168.1.1:58247: Get "https://acme-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority
```

```yml
---
server_url: https://urskog.ddns.net
listen_addr: 0.0.0.0:443
ip_prefix: 100.64.0.0/10
log_level: debug
private_key_path: private.key
db_type: postgres
db_host: postgres
db_port: 5432
db_name: headscale
db_user: foo
db_pass: bar
derp_map_path: derp.yaml
ephemeral_node_inactivity_timeout: 30m
#tls_cert_path: ""
#tls_key_path: ""
tls_letsencrypt_hostname: urskog.ddns.net
tls_letsencrypt_cache_dir: tls_cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: :http
dns_config:
  nameservers:
    - 1.1.1.1
```

**Comment by cure** [comment] 2021-10-03 18:03
This worked for me as recently as yesterday. 

It looks like your computer can not establish a TLS handshake with the Let's Encrypt directory endpoint at "https://acme-v02.api.letsencrypt.org/directory". Maybe your local list of CA certificates is out of date?

**Comment by urskog84** [comment] 2021-10-04 15:50
I use the docker image, from https://hub.docker.com/u/headscale

FROM headscale/headscale:0.9.2

**Comment by juanfont** [comment] 2021-10-16 10:41
@urskog84 are you still having this issue?

**Comment by cure** [comment] 2021-10-31 14:01
> _@juanfont I'm getting this error as well, using the docker image headscale/headscale:latest_
> 
> EDIT: I updated to the image that was pushed recently and it's now working just fine!

That confirms what I thought; this was caused by the Let's Encrypt root cert change, and the new docker images have the necessary updates. Closing this issue.

**Closed by cure** 2021-10-31 14:01 UTC
Labels: bug
