### ISSUE TITLE
add --verify-clients option to embedded DERP server  as tailscale derper support it

### ISSUE THREAD

**Issue by heygo1345678** [juanfont/headscale#1143] opened 2023-01-17 13:53 UTC
Anyone that knows the IP address of your DERP node could add it to their DERP map and route their tailnet traffic through your DERP node. To allow only your tailnet traffic through your DERP node, run tailscaled on the same machine as your DERP node, and start derper with the --verify-clients flag:

sudo derper --hostname=your-hostname.com --verify-clients

**Comment by vampywiz17** [comment] 2023-01-27 08:46
https://github.com/juanfont/headscale/issues/740

I think it impact a huge performance problem if that not add it to embedded DERP server.... Please do this.

**Comment by juanfont** [comment] 2023-02-05 09:42
This is a duplicate of #740

**Closed by juanfont** 2023-02-05 09:42 UTC
Labels: enhancement
