### ISSUE TITLE
Wildcard DNS-Records

### ISSUE THREAD

**Issue by Neon-44** [juanfont/headscale#1840] opened 2024-03-20 17:47 UTC
## Why

I use Headscale to securely selfhost my Applications. Currently i just route the Local IPs to my Server and force all my Tailscale Devices to use the Local DNS-Server. however, if i could define the Domains in the Headscale DNS-Config (Via a Wildcard in the best Case) i could stop advertising local routes and instead resolve those Domains to the Tailscale Domain.

I would prefer Wildcards, as i sometimes add / remove Services with unique subdomains and I'm a bit scared of a indent-mistake in the config when adding the new record bringing the Server down, locking me out.

## Description

currently the DNS of Headscale (this one: https://github.com/juanfont/headscale/blob/main/docs/dns-records.md#Limitations) can only resolve specific Domains. I would like to be able to put a wildcard in there and all subdomains getting redirected off of that Wildcard

**Comment by Neon-44** [comment] 2024-06-24 17:55
hey, can I get a quick feedback instead of just a stale? even if it's a wontfix, just so we know what's up.

**Comment by dennisoderwald** [comment] 2024-09-23 08:57
Ping :)

**Comment by warlordattack** [comment] 2024-09-29 18:27
Hello perhaps the same subject, i like to have nice local dns names, 
-in the LAN i use AdGuard to rewrite all local DNS names to traefik with one rule using wildcard : see picture
-headscale there is " dns: > extra_records: " section for this, but unfortunatly you must add all your local dns names one by one : see picture

![image](https://github.com/user-attachments/assets/4e296149-ce2d-4db7-bc8b-467aaefecd73)

Would be very nice to have record like this (to replace all the individual lines) : 
![image](https://github.com/user-attachments/assets/241df073-adcd-49d9-aac6-2ffb4117ce28)

Best regards :)

**Comment by kradalby** [comment] 2024-11-22 11:17
I think this is a duplicate of #2159, I've replied there that it needs investigation, but I think it is a client limitation we cant do anything about. If it does currently not work, it probably wont as we just pass the option straight too the client.

**Closed by kradalby** 2024-11-22 11:17 UTC
Labels: enhancement

**Comment by Neon-44** [comment] 2024-11-24 07:34
wait, but this Issue is older?

Shouldn't you mark 2159 as a duplicate of 1840, the older one?

oh well, whatever, I'll check it out over there.
