### ISSUE TITLE
Sqlite and Sqlite3 db types fail to start with "out of memory" on v0.23.0-alpha4

### ISSUE THREAD

**Issue by Nickiel12** [juanfont/headscale#1774] opened 2024-02-17 20:48 UTC
## Bug description
After updating from headscale v0.23.0-alpha3, to v0.23.0-alpha4, I am unable to start headscale and encounter this error in my journalctl output:

`FTL github.com/juanfont/headscale/cmd/headscale/cli/server.go:21 > Error initializing error="unable to open database file: out of memory (14)"`

A side note, but I also had to change the "settings.db_type" setting to "settings.database.type" in my nix config. It would be nice to implement a depreciation warning on this setting in the repository's flake.nix.

## Environment

- headscale v0.23.0-alpha4
- Tailscale 1.60.0
- NixOS 24.05 - unstable

I have nginx running with a proxypass to headscale, but I've been succesfully using that for a while

## To Reproduce
Install headscale v0.23.0-alpha4 with the following settings:

```nix
  services.headscale = {
    package = headscale.packages.${pkgs.system}.headscale; // using the flake
    enable = true;
    address = "0.0.0.0";
    port = 8082;
    settings = {
      server_url = "https://${domain}";
      database.type = "sqlite3";
      dns_config = {
        base_domain = baseDomain;
        extra_records = tailscale_dns_entries;
      };
      derp = {
        auto_update_enable = true;
        update_frequency = "24h";
      };
    };
  };
```

**Comment by kradalby** [comment] 2024-02-18 18:44
Duplicate of #1761, fixed in main.

**Closed by kradalby** 2024-02-18 18:44 UTC
Labels: bug
