### ISSUE TITLE
[Bug] TLS internal error when attempting to login

### ISSUE THREAD

**Issue by Noodlez1232** [juanfont/headscale#1988] opened 2024-06-20 09:50 UTC
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to use `tailscale up` or using a different device (e.g. android), the command line locks up, and tailscaled gives the error `Received error: fetch control key: Get "https://<host>key?v=95": remote error: tls: internal error`

### Expected Behavior

`tailscale up` works, and gives a login URL to use.

### Steps To Reproduce

1. Setup Headscale using NixOS module.
2. Set `services.headscale.package` to the package given in the flake in the repo
3. Set up Headscale behind a Caddy reverse proxy (`reverse_proxy localhost:9900`)
4. Try to login

### Environment

```markdown
- OS: NixOS 24.03
- Headscale version: main (also occurs on 0.22.3 and 0.23.0-alpha12)
- Tailscale version: 1.66.4 (also occurs on 1.68.0)
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

All other TLS works, and when using `localhost` as the login url, tailscale will login, meaning it has something to do with the reverse proxy. Where my trouble is is that headscale is the only application with this TLS problem.

**Comment by ohdearaugustin** [comment] 2024-06-20 10:18
Please for reverse_proxy join discord and discuss there. This is not a bug, rather a support request.
Will close the issue.

**Closed by ohdearaugustin** 2024-06-20 10:18 UTC
Labels: bug
