### ISSUE TITLE
Version sub command always shows "dev"

### ISSUE THREAD

**Issue by x86dev** [juanfont/headscale#635] opened 2022-06-12 06:41 UTC
As the title says, the version sub command always shows "dev". It would very useful to show the real / tagged version number (e.g. 0.16-beta3 as of writing) to see if already running the latest and greatest version.

**Comment by huskyii** [comment] 2022-06-12 09:01
Makefile has this feature, however, it has a bug... In my dev machine, it print nothing, could you provide your setup?

You can manually specify version through `make build version=v0.16.0-beta3`

**Comment by kradalby** [comment] 2022-06-12 11:40
I suspect the problem here is that it isnt passed via Go Releaser, which is what produces the binaries "most" people download.

**Comment by kradalby** [comment] 2022-06-12 11:52
@x86dev Where do you see this behaviour? I just pulled down the binaries from the release page and all of them has the correct version.

**Comment by x86dev** [comment] 2022-06-12 13:06
I'm pulling my headscale server via headscale/headscale:latest, which currently is at 25f15f64c292 (21 hours ago as of writing). When I issue a  ``docker exec <my-container> headscale version`` it just returns "dev".

**Comment by kradalby** [comment] 2022-06-12 13:14
ah, in that case its a duplicate of #186, closing as duplicate.

**Closed by kradalby** 2022-06-12 13:14 UTC
Labels: bug

**Comment by x86dev** [comment] 2022-06-12 14:04
Ah good, wasn't aware of #186. Thanks!
